@startjson
{
    "results": {
        "sunrise": "9:09:15 AM",
        "sunset": "8:59:13 PM",
        "solar_noon": "3:04:14 PM",
        "day_length": "11:49:58",
        "civil_twilight_begin": "8:47:47 AM",
        "civil_twilight_end": "9:20:40 PM",
        "nautical_twilight_begin": "8:21:36 AM",
        "nautical_twilight_end": "9:46:52 PM",
        "astronomical_twilight_begin": "7:55:25 AM",
        "astronomical_twilight_end": "10:13:02 PM"
    },
    "status": "OK"
}
@endjson