@startuml
title "Coleta do Historico"

start
:Limpar base existente;
:Definir data inicial da coleta;
:Definir data final da coleta para dia anterior;

repeat
	:Pega data das medicoes;
	:Obtem dados das medicoes de clima da API de clima;
	:Obtem horas de nascer e por do sol da API de sunset/sunrise;
	:Trata os dados;
	:Salva os dados tratados no DW;
	:Incrementa a data em 1 dia;
repeat while (Estourou o limite?) is (Nao)
->Sim;
end
@enduml