@startuml
!include <aws/common>
!include <aws/Compute/AWSLambda/AWSLambda>
!include <aws/Database/AmazonDynamoDB/AmazonDynamoDB>

!include <awslib/AWSCommon>
!include <awslib/InternetOfThings/IoTRule>
!include <awslib/ApplicationIntegration/SimpleQueueService>

!include <azure/AzureCommon>
!include <azure/Analytics/AzurePowerBIEmbedded>

!include <cloudinsight/tomcat>
!include <cloudinsight/kafka>
!include <cloudinsight/java>
!include <cloudinsight/cassandra>

!include <elastic/endpoint/endpoint>

title "Arquitetura da Solucao"

cloud {
	ENDPOINT(weather_api, "Weather API")
}

cloud "AWS" {
	AWSLAMBDA(collect_app, "Weather Collect Script")
	AMAZONDYNAMODB(analytics_weather_db, "Weather DB")

	weather_api <-- collect_app
	collect_app -> analytics_weather_db
}


sprite $AzurePowerBIEmbedded [70x70/16z] {
xTZNaSDG34DHIGH5zT_mHexX0Dl2vl1k0MVmZMbVo6uzb9WdBpJHI9UcqiXvfg88NraLuYkYeGnbA5OpyYLR2Pcfp5h93r7mUSfGy7u50UG9Khu2u4mfLq6W
5HBbAkYebAk029A4fw2ZKhw2KuM4eU2iB5y1V6LUH64gY-xlAaCPob0oFq39ToWatg_a-vKy8ElRb6Za7Key1HAkGYIGbYA8syfMssqb6f4A4QsGO7ccaDXk
A2Ja5Y9Q4OJQqiGj9NOeH9GY2A6Gq4hiKhPVf2o-KfDWN6Nbk_K8
}
AzureEntityColoring(AzurePowerBIEmbedded)

rectangle "Dashboard" <<$AzurePowerBIEmbedded>> as dashboard
dashboard <-- analytics_weather_db

@enduml